### ISSUE TITLE
Non-recursive listing

### ISSUE THREAD

**Issue by dipcore** [gryf/mc_adbfs#2]
Is it possible to make the initial listing non recursive,
and then just read directory content by opening it?

**Comment by dipcore** [comment]
Huh, I just read more about it, it seems like it's limitation of extfs plugins. :(

**Comment by gryf** [comment]
Right. Extfs expects to get entire listing, unfortunately. It is possible for providing VFS written in C and compile it with MC sources, which will do what you want (just like ftpfs for instance), but it requires more effort than just simple drop-in like this one.

I know, that grabbing the file listing take a lot of time, that's why I've introduced configurable `root` option, which narrow down the necessity of reading only this directory and its subdirs. What I usually want is to access /storage/emulated/0, which is the place where Android write shared files like photos, downloads and so on.

I close it, since it's not relevant for this particular extfs plugin.
